#!/bin/bash

# Libraries for NL & Machine Learning
export DEBIAN_FRONTEND=noninteractive && \
      apt-get update && \
      apt-get install -y --allow-unauthenticated \
      g++ \
      git \
      libopenblas-dev \
      python$tag-nose \
      python$tag-numpy \
      python$tag-scipy \
      gfortran && \
      apt-get purge -y && \
      chown -R root:root $HOME && \
      pip$tag install --user -r /tmp/scipy/requirements.txt && \
      python$tag -m textblob.download_corpora && \
      python$tag -m spacy.en.download && \
      chown -R sandbox:sandbox $HOME && \
      rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
